%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
clear global
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'dynare_opt_policy';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'dynare_opt_policy.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'shock1';
M_.exo_names_tex = 'shock1';
M_.exo_names = char(M_.exo_names, 'shock2');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock2');
M_.endo_names = 'zz';
M_.endo_names_tex = 'zz';
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names = char(M_.endo_names, 'brF');
M_.endo_names_tex = char(M_.endo_names_tex, 'brF');
M_.endo_names = char(M_.endo_names, 'pE');
M_.endo_names_tex = char(M_.endo_names_tex, 'pE');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names = char(M_.endo_names, 'intr');
M_.endo_names_tex = char(M_.endo_names_tex, 'intr');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names = char(M_.endo_names, 'Cmin');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cmin');
M_.endo_names = char(M_.endo_names, 'Smin');
M_.endo_names_tex = char(M_.endo_names_tex, 'Smin');
M_.endo_names = char(M_.endo_names, 'Nmin');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nmin');
M_.endo_names = char(M_.endo_names, 'brFmin');
M_.endo_names_tex = char(M_.endo_names_tex, 'brFmin');
M_.endo_names = char(M_.endo_names, 'intrmin');
M_.endo_names_tex = char(M_.endo_names_tex, 'intrmin');
M_.endo_names = char(M_.endo_names, 'Splus');
M_.endo_names_tex = char(M_.endo_names_tex, 'Splus');
M_.endo_names = char(M_.endo_names, 'inflplus');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflplus');
M_.endo_names = char(M_.endo_names, 'Cplus');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cplus');
M_.endo_names = char(M_.endo_names, 'Zplus');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zplus');
M_.endo_names = char(M_.endo_names, 'Kplus');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kplus');
M_.endo_names = char(M_.endo_names, 'G1');
M_.endo_names_tex = char(M_.endo_names_tex, 'G1');
M_.endo_names = char(M_.endo_names, 'G2');
M_.endo_names_tex = char(M_.endo_names_tex, 'G2');
M_.endo_names = char(M_.endo_names, 'G3');
M_.endo_names_tex = char(M_.endo_names_tex, 'G3');
M_.endo_names = char(M_.endo_names, 'G4');
M_.endo_names_tex = char(M_.endo_names_tex, 'G4');
M_.endo_names = char(M_.endo_names, 'G5');
M_.endo_names_tex = char(M_.endo_names_tex, 'G5');
M_.endo_names = char(M_.endo_names, 'G6');
M_.endo_names_tex = char(M_.endo_names_tex, 'G6');
M_.endo_names = char(M_.endo_names, 'G7');
M_.endo_names_tex = char(M_.endo_names_tex, 'G7');
M_.endo_names = char(M_.endo_names, 'G8');
M_.endo_names_tex = char(M_.endo_names_tex, 'G8');
M_.endo_names = char(M_.endo_names, 'G9');
M_.endo_names_tex = char(M_.endo_names_tex, 'G9');
M_.endo_names = char(M_.endo_names, 'G10');
M_.endo_names_tex = char(M_.endo_names_tex, 'G10');
M_.endo_names = char(M_.endo_names, 'G11');
M_.endo_names_tex = char(M_.endo_names_tex, 'G11');
M_.endo_names = char(M_.endo_names, 'G12');
M_.endo_names_tex = char(M_.endo_names_tex, 'G12');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names = char(M_.param_names, 'ust');
M_.param_names_tex = char(M_.param_names_tex, 'ust');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names = char(M_.param_names, 'k');
M_.param_names_tex = char(M_.param_names_tex, 'k');
M_.param_names = char(M_.param_names, 'a');
M_.param_names_tex = char(M_.param_names_tex, 'a');
M_.param_names = char(M_.param_names, 'z');
M_.param_names_tex = char(M_.param_names_tex, 'z');
M_.param_names = char(M_.param_names, 'phist');
M_.param_names_tex = char(M_.param_names_tex, 'phist');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names = char(M_.param_names, 'Xst');
M_.param_names_tex = char(M_.param_names_tex, 'Xst');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names = char(M_.param_names, 'qst');
M_.param_names_tex = char(M_.param_names_tex, 'qst');
M_.param_names = char(M_.param_names, 'Sst');
M_.param_names_tex = char(M_.param_names_tex, 'Sst');
M_.param_names = char(M_.param_names, 'Nst');
M_.param_names_tex = char(M_.param_names_tex, 'Nst');
M_.param_names = char(M_.param_names, 'Cst');
M_.param_names_tex = char(M_.param_names_tex, 'Cst');
M_.param_names = char(M_.param_names, 'Zst');
M_.param_names_tex = char(M_.param_names_tex, 'Zst');
M_.param_names = char(M_.param_names, 'pEst');
M_.param_names_tex = char(M_.param_names_tex, 'pEst');
M_.param_names = char(M_.param_names, 'Kst');
M_.param_names_tex = char(M_.param_names_tex, 'Kst');
M_.param_names = char(M_.param_names, 'brFst');
M_.param_names_tex = char(M_.param_names_tex, 'brFst');
M_.param_names = char(M_.param_names, 'intrst');
M_.param_names_tex = char(M_.param_names_tex, 'intrst');
M_.param_names = char(M_.param_names, 'Yst');
M_.param_names_tex = char(M_.param_names_tex, 'Yst');
M_.param_names = char(M_.param_names, 'inflst');
M_.param_names_tex = char(M_.param_names_tex, 'inflst');
M_.param_names = char(M_.param_names, 'thetast');
M_.param_names_tex = char(M_.param_names_tex, 'thetast');
M_.param_names = char(M_.param_names, 'xcoef');
M_.param_names_tex = char(M_.param_names_tex, 'xcoef');
M_.param_names = char(M_.param_names, 'Gs1');
M_.param_names_tex = char(M_.param_names_tex, 'Gs1');
M_.param_names = char(M_.param_names, 'Gs2');
M_.param_names_tex = char(M_.param_names_tex, 'Gs2');
M_.param_names = char(M_.param_names, 'Gs3');
M_.param_names_tex = char(M_.param_names_tex, 'Gs3');
M_.param_names = char(M_.param_names, 'Gs4');
M_.param_names_tex = char(M_.param_names_tex, 'Gs4');
M_.param_names = char(M_.param_names, 'Gs5');
M_.param_names_tex = char(M_.param_names_tex, 'Gs5');
M_.param_names = char(M_.param_names, 'Gs6');
M_.param_names_tex = char(M_.param_names_tex, 'Gs6');
M_.param_names = char(M_.param_names, 'Gs7');
M_.param_names_tex = char(M_.param_names_tex, 'Gs7');
M_.param_names = char(M_.param_names, 'Gs8');
M_.param_names_tex = char(M_.param_names_tex, 'Gs8');
M_.param_names = char(M_.param_names, 'Gs9');
M_.param_names_tex = char(M_.param_names_tex, 'Gs9');
M_.param_names = char(M_.param_names, 'Gs10');
M_.param_names_tex = char(M_.param_names_tex, 'Gs10');
M_.param_names = char(M_.param_names, 'Gs11');
M_.param_names_tex = char(M_.param_names_tex, 'Gs11');
M_.param_names = char(M_.param_names, 'Gs12');
M_.param_names_tex = char(M_.param_names_tex, 'Gs12');
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 38;
M_.param_nbr = 39;
M_.orig_endo_nbr = 38;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.H = 0;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('dynare_opt_policy_static');
erase_compiled_function('dynare_opt_policy_dynamic');
M_.lead_lag_incidence = [
 1 15 0;
 2 16 0;
 3 17 53;
 4 18 0;
 5 19 54;
 0 20 0;
 0 21 55;
 0 22 0;
 6 23 0;
 7 24 0;
 0 25 56;
 0 26 0;
 8 27 57;
 0 28 0;
 0 29 58;
 0 30 59;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 9 41 60;
 10 42 0;
 11 43 0;
 0 44 0;
 12 45 0;
 13 46 0;
 14 47 0;
 0 48 61;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 62;]';
M_.nstatic = 18;
M_.nfwrd   = 6;
M_.npred   = 10;
M_.nboth   = 4;
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(39, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 162;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.sigma_e_is_diagonal = 1;
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 0;
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save('dynare_opt_policy_results.mat', 'oo_', 'M_', 'options_');


disp(['Total computing time : ' dynsec2hms(toc) ]);
diary off
